services:
  api-db:
    image: "postgres"
    container_name: "api-db"
    environment:
      POSTGRES_PASSWORD: localdbpwd
      POSTGRES_DB: api-db
      POSTGRES_USER: localdbusr
    ports:
      - "5432:5432"